//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLGDB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CauThu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CauThu()
        {
            this.DoiBongCauThus = new HashSet<DoiBongCauThu>();
        }
    
        public int Id { get; set; }
        public string Msv { get; set; }
        public string HoTen { get; set; }
        public string TenLop { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoiBongCauThu> DoiBongCauThus { get; set; }
    }
}
