//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLGDB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoiBongCauThu
    {
        public int Id { get; set; }
        public Nullable<int> IdDoi { get; set; }
        public Nullable<int> IdCauThu { get; set; }
    
        public virtual CauThu CauThu { get; set; }
        public virtual DoiBong DoiBong { get; set; }
    }
}
