//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLGDB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichThiDau
    {
        public int Id { get; set; }
        public Nullable<int> IdGiai { get; set; }
        public Nullable<int> IdDoi1 { get; set; }
        public Nullable<int> IdDoi2 { get; set; }
        public Nullable<System.DateTime> ThoiThiDau { get; set; }
        public Nullable<int> SBTDOI1 { get; set; }
        public Nullable<int> SBTDOI2 { get; set; }
        public Nullable<int> TranDau { get; set; }
        public Nullable<int> IdDoiWin { get; set; }
    
        public virtual DoiBong DoiBong { get; set; }
        public virtual DoiBong DoiBong1 { get; set; }
        public virtual GiaiDau GiaiDau { get; set; }
    }
}
